import { Role } from "@prisma/client";
import { hashSync } from "bcrypt-ts-edge";
import { generateRsvpCode } from "@/lib/utils";

export const users = [
  {
    id: "user-admin-1",
    name: "Admin Renaldi",
    email: "admin@event.com",
    password: hashSync("12345678", 10),
    role: Role.ADMIN,
  },
  {
    id: "user-resepsionis-1",
    name: "Resepsionis Cici",
    email: "resepsionis@event.com",
    password: hashSync("12345678", 10),
    role: Role.RESEPSIONIS,
  },
];

export const guests = [
  {
    id: "guest-001",
    name: "Budi Santoso",
    phone: "08123456789",
    rsvpCode: generateRsvpCode("Budi Santoso", "08123456789"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Terima kasih undangannya!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-002",
    name: "Siti Aminah",
    phone: "08987654321",
    rsvpCode: generateRsvpCode("Siti Aminah", "08987654321"),
    isRSVPed: true,
    isAttending: false,
    isPresent: false,
    greetingMessage: "Mohon maaf tidak bisa hadir.",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-003",
    name: "Joko Suwiarto",
    phone: "08955654321",
    rsvpCode: generateRsvpCode("Joko Suwiarto", "08955654321"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-004",
    name: "Ani Wijaya",
    phone: "08111222333",
    rsvpCode: generateRsvpCode("Ani Wijaya", "08111222333"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Sampai jumpa di hari bahagia!",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-005",
    name: "Rudi Hartono",
    phone: "08223344556",
    rsvpCode: generateRsvpCode("Rudi Hartono", "08223344556"),
    isRSVPed: true,
    isAttending: false,
    isPresent: false,
    greetingMessage: "Maaf belum bisa hadir.",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-006",
    name: "Yuni Kartika",
    phone: "08312355667",
    rsvpCode: generateRsvpCode("Yuni Kartika", "08312355667"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-007",
    name: "Andi Pratama",
    phone: "08445566422",
    rsvpCode: generateRsvpCode("Andi Pratama", "08445566422"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Selamat menempuh hidup baru!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-008",
    name: "Dina Sari",
    phone: "08333677889",
    rsvpCode: generateRsvpCode("Dina Sari", "08333677889"),
    isRSVPed: true,
    isAttending: false,
    isPresent: false,
    greetingMessage: "Semoga acaranya lancar!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-009",
    name: "Eko Nugroho",
    phone: "08667745690",
    rsvpCode: generateRsvpCode("Eko Nugroho", "08667745690"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-010",
    name: "Fitri Maulida",
    phone: "08668899001",
    rsvpCode: generateRsvpCode("Fitri Maulida", "08668899001"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Terima kasih telah mengundang kami!",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-011",
    name: "Hasan Albar",
    phone: "08786900112",
    rsvpCode: generateRsvpCode("Hasan Albar", "08786900112"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Acaranya luar biasa!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-012",
    name: "Nina Larasati",
    phone: "08112233445",
    rsvpCode: generateRsvpCode("Nina Larasati", "08112233445"),
    isRSVPed: true,
    isAttending: true,
    isPresent: false,
    greetingMessage: "Maaf ada halangan datang.",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-013",
    name: "Galih Prakoso",
    phone: "08223214556",
    rsvpCode: generateRsvpCode("Galih Prakoso", "08223214556"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-014",
    name: "Intan Permata",
    phone: "08334455667",
    rsvpCode: generateRsvpCode("Intan Permata", "08334455667"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Congrats buat pengantinnya!",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-015",
    name: "Rizky Hidayat",
    phone: "08445566778",
    rsvpCode: generateRsvpCode("Rizky Hidayat", "08445566778"),
    isRSVPed: true,
    isAttending: false,
    isPresent: false,
    greetingMessage: "Semoga jadi keluarga sakinah!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-016",
    name: "Mega Ayu",
    phone: "08556677889",
    rsvpCode: generateRsvpCode("Mega Ayu", "08556677889"),
    isRSVPed: true,
    isAttending: true,
    isPresent: false,
    greetingMessage: "Semoga bahagia selalu!",
    updatedById: "user-admin-1",
  },
  {
    id: "guest-017",
    name: "Bayu Saputra",
    phone: "08667788990",
    rsvpCode: generateRsvpCode("Bayu Saputra", "08667788990"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-018",
    name: "Lia Marlina",
    phone: "08778899001",
    rsvpCode: generateRsvpCode("Lia Marlina", "08778899001"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Terima kasih sudah mengundang!",
    updatedById: "user-resepsionis-1",
  },
  {
    id: "guest-019",
    name: "Fajar Nugraha",
    phone: "08889900112",
    rsvpCode: generateRsvpCode("Fajar Nugraha", "08889900112"),
    isRSVPed: false,
    isAttending: null,
    isPresent: false,
    greetingMessage: "",
    updatedById: null,
  },
  {
    id: "guest-020",
    name: "Tari Ramadhani",
    phone: "08990011223",
    rsvpCode: generateRsvpCode("Tari Ramadhani", "08990011223"),
    isRSVPed: true,
    isAttending: true,
    isPresent: true,
    greetingMessage: "Doa terbaik untuk pengantinnya!",
    updatedById: "user-admin-1",
  },
];

export const logs = [
  {
    guestId: "guest-001",
    userId: "user-resepsionis-1",
    action: "checked-in",
  },
  {
    guestId: "guest-002",
    userId: "user-admin-1",
    action: "rsvp-submit",
  },
  {
    guestId: "guest-004",
    userId: "user-resepsionis-1",
    action: "checked-in",
  },
  {
    guestId: "guest-007",
    userId: "user-resepsionis-1",
    action: "checked-in",
  },
  {
    guestId: "guest-010",
    userId: "user-admin-1",
    action: "checked-in",
  },
  {
    guestId: "guest-011",
    userId: "user-resepsionis-1",
    action: "checked-in",
  },
  {
    guestId: "guest-014",
    userId: "user-admin-1",
    action: "checked-in",
  },
  {
    guestId: "guest-018",
    userId: "user-resepsionis-1",
    action: "checked-in",
  },
  {
    guestId: "guest-020",
    userId: "user-admin-1",
    action: "checked-in",
  },
];
